-- vim.defer_fn(function()
--     vim.cmd('packadd copilot')
--     require("copilot").setup({
--         suggestion = {enabled = false},
--         panel = {enabled = false}
--     })
--     require("copilot_cmp").setup()
-- end, 100)
